### PR TITLE
Use consistent formatting

### PR DESCRIPTION
**Pull request by vincentdoerig**
Hey, I cleaned up the file and used some mconsistent formatting

- use single quotes consistently
- fix indentations
- remove commented console.logs 

the variable `userId` on line 11 is not used anywhere, should I remove it?

### CODE REVIEW

**Comment by thomaschaplin** [comment]
@vincentdoerig it looks like `userId` is only referenced [here](https://github.com/appwrite/playground-for-deno/blob/master/mod.ts#L104) which means you could convert like 104 to `const userId = response.$id;`. However, saying that it also looks like like 104 isn't used anywhere either so I think lines 11 and 104 could be removed? Let's see what one of the maintainers say.

**Comment by thomaschaplin** [comment]
@vincentdoerig I believe your changes regarding your below two points should be strongly considered against (see below for reason).

* use single quotes consistently
* fix indentations

I feel strongly about using a standardised formatting/linting method and using deno's built in `deno fmt` cli should be the way this is handled (imo).

Using `deno fmt` would be consistent going forwards instead of implementing a ad-hoc linting rule of single quotes over double quotes. These are of course my opinions, what do you think @punitdiwan @eldadfux ?

The main reason for this comment is that it would almost revert the changes I made in the PR https://github.com/appwrite/playground-for-deno/pull/6 where I have used the `deno fmt` command to apply linting.

I don't mean to offend any contributions but I feel consistency is key when it comes to linting / formatting.

**Comment by vincentdoerig** [comment]
Yup, this is a fair point, I didn't take deno's default linting rules into account. I have reverted the changes.

**Review by punitdiwan — APPROVED** [review]
As far as formatting is concerned, I suggest that we should use  deno fmt command as its officially supported by deno. This PR looks fine to me and can be merged in main (master).

**Comment by punitdiwan** [comment]
@vincentdoerig Thanks for your valuable changes.
@thomaschaplin  Thanks for your valuable  comments.

**Comment by eldadfux** [comment]
THANK YOU @vincentdoerig ! All changes merged 🥳

Thanks @punitdiwan for helping with the review process!

@vincentdoerig, Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like me to send you some cool Appwrite stickers and magnets! Please note that shipping might take longer times because of COVID19.

As a way of saying thank you, we have just invited you to join the Appwrite organization on GitHub. You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

**Pull request merged**
