### PR TITLE
refactor source for future extensibilty

### PR DESCRIPTION
**Pull request by celeroncoder**
- Separated user, document and collection API code into different namespaces inside different files.
- Moved all the API calls into an async IIFE.
- updated readme run command since `mod.ts` moved to `src` directory.

### CODE REVIEW

**Comment by PineappleIOnic** [comment]
This is quite a large change, is there a issue for it that you were assigned to?

**Review by Meldiron — CHANGES_REQUESTED** [review]
This looks like a big change, can we do a test to make sure it works properly? Can you please share a screenshot of the successful execution?

**Review by Meldiron — CHANGES_REQUESTED** [review]
Marking this as change request

**Comment by celeroncoder** [comment]
> This is quite a large change, is there a issue for it that you were assigned to?

@PineappleIOnic No this was not an issue, I just went for it 😅.

**Comment by celeroncoder** [comment]
@Meldiron 

Here are the screenshots of successful execution. 😄 

Screenshot from 2021-10-29 19-32-00

**screenshot for created collection**
 
Screenshot from 2021-10-29 19-32-35

**screenshot for the successful file uploads**
Screenshot from 2021-10-29 19-37-24

**Comment by christyjacob4** [comment]
@khushalbhardwaj-0111 Can you please resolve the merge conflict ?

**Comment by celeroncoder** [comment]
> @khushalbhardwaj-0111 Can you please resolve the merge conflict ?

The merge conflict is 'cuz I moved the `mod.ts` file to the [src](https://github.com/khushalbhardwaj-0111/playground-for-deno/blob/refactor-source/src/mod.ts) folder.

**Comment by christyjacob4** [comment]
@khushalbhardwaj-0111 That shouldn't cause the merge conflict.  

You need to 
1. first checkout to your branch 
2. `git pull origin master`
3. fix the merge conflicts
4. commit the changes
5. push to your branch 

🙃

**Comment by celeroncoder** [comment]
@christyjacob4 resolved the merge conflicts thanks a lot for help 😅 .

**Comment by christyjacob4** [comment]
THANK YOU! All changes merged :partying_face:

Please ready out to me on discord to claim your hacktoberfest swag. 

As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord so that we can add you as a contributor to our organization.

Once added, you can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite membership badge will show up on your personal GitHub profile.

**Pull request merged**
