### PR TITLE
Initial Code for Deno Playground

### PR DESCRIPTION
**Pull request by punitdiwan**
I have added initial Code for the Deno playground with updated Readme.md file. Currently covering the following features.

- addDoc
- listDoc
- uploadFile
- createUser

### CODE REVIEW

**Comment by punitdiwan** [comment]
### API Covered in Playground.
* Create Collection
* List Collection
* Add Document
* List Documents
* Upload File
* Create User
* List User

**Comment by eldadfux** [comment]
Great work @punitdiwan, one thing I would consider changing is dropping the api.ts file and include all API calls directly in mod.ts file with no class or method wrapping for greater visibility.

**Comment by eldadfux** [comment]
This project can also be an excellent boilerplate for other server playground for php, node, ruby, dart and others.

**Comment by punitdiwan** [comment]
I can definitely make all method in one file. The reason I did that was because I was passing CollectionID of CreateCollection API to  GetCollection API. I can also change it to One File (mod.ts)

**Comment by eldadfux** [comment]
Great, once your'e ready, I'll merge the PR and create an announcement post for the Deno SDK release. This also allows us to officially support the Deno env for cloud functions from day 1.

**Comment by punitdiwan** [comment]
PR is ready to merge. I have removed the api.ts and used all the api declaration in mod.ts as per your suggestion. I have added Console Messages with White Background and Green Fore ground color for better visibility.

**Pull request merged**
